### ISSUE TITLE
Syntax issue

### ISSUE THREAD

**Issue by ladrua** [akirak/poly-vue#2]
Hi! I found your rep a while ago and have been using your code for a few weeks. I find that the syntax highlighting is buggy. Mainly issue for script. Using js2-mode. Odd thing is that if I `revert-buffer` it sometimes loads as expected. Or sometimes if I edit the `<script>` tag it also just start working(adding a space at the end, then removing it`<script >`).
You still using this setup? Have you had any similar issues? Thanks!

**Comment by akirak** [comment]
I am not writing Vue.js now, nor am I using poly-mode in general. As far as I remember, this stuff didn't perfectly work even when I was using it. Sorry for the issue.

Here are some alternatives I would suggest to use:

- mmm-mode, which I used for writing React this year. Works relatively well.
- web-mode
- [tree-sitter-mode](https://emacs-tree-sitter.github.io/getting-started/) combined with a [tree-sitter](https://tree-sitter.github.io/tree-sitter/) parser

Thanks for trying out my package. Maybe I'll archive this repository soon.
